2020-02-07 15:04:20,132 - D:/罗京/Projects/cmdb/app.py[line:38] - ERROR: 'list' object has no attribute 'id'
2020-02-07 15:05:32,787 - D:/罗京/Projects/cmdb/app.py[line:40] - ERROR: 'list' object has no attribute 'id'
2020-02-11 12:32:59,453 - D:/罗京/Projects/cmdb/app.py[line:47] - ERROR: 'str' object has no attribute 'get'
2020-02-11 12:35:14,326 - D:/罗京/Projects/cmdb/app.py[line:47] - ERROR: 'str' object has no attribute 'get'
2020-02-11 12:47:36,807 - D:/罗京/Projects/cmdb/app.py[line:47] - ERROR: 'str' object has no attribute 'get'
2020-02-11 16:20:45,885 - D:/罗京/Projects/cmdb/app.py[line:311] - ERROR: 'Field' object has no attribute 'items'
2020-02-11 16:22:08,203 - D:/罗京/Projects/cmdb/app.py[line:311] - ERROR: 'Field' object has no attribute 'items'
2020-02-11 19:35:46,184 - D:/罗京/Projects/cmdb/app.py[line:146] - ERROR: unsupported operand type(s) for &: 'bool' and 'BinaryExpression'
2020-02-11 19:35:53,411 - D:/罗京/Projects/cmdb/app.py[line:146] - ERROR: unsupported operand type(s) for &: 'bool' and 'BinaryExpression'
2020-02-11 19:57:35,810 - D:/罗京/Projects/cmdb/app.py[line:146] - ERROR: unsupported operand type(s) for &: 'bool' and 'BinaryExpression'
2020-02-11 23:57:55,724 - D:/罗京/Projects/cmdb/app.py[line:107] - ERROR: 'NoneType' object is not iterable
2020-02-12 12:40:18,866 - D:/罗京/Projects/cmdb/app.py[line:108] - ERROR: 'NoneType' object has no attribute 'todict'
2020-02-12 12:43:01,407 - D:/罗京/Projects/cmdb/app.py[line:108] - ERROR: 'NoneType' object has no attribute 'todict'
2020-02-12 12:43:53,054 - D:/罗京/Projects/cmdb/app.py[line:108] - ERROR: 'NoneType' object has no attribute 'todict'
2020-02-12 12:47:48,726 - D:/罗京/Projects/cmdb/app.py[line:108] - ERROR: 'NoneType' object has no attribute 'todict'
2020-02-12 12:47:55,201 - D:/罗京/Projects/cmdb/app.py[line:108] - ERROR: 'NoneType' object has no attribute 'todict'
2020-02-12 12:49:10,995 - D:/罗京/Projects/cmdb/app.py[line:108] - ERROR: 'NoneType' object has no attribute 'todict'
2020-02-12 12:49:30,016 - D:/罗京/Projects/cmdb/app.py[line:108] - ERROR: 'NoneType' object has no attribute 'todict'
2020-02-12 12:50:11,201 - D:/罗京/Projects/cmdb/app.py[line:108] - ERROR: 'NoneType' object has no attribute 'todict'
2020-02-12 12:50:17,606 - D:/罗京/Projects/cmdb/app.py[line:108] - ERROR: 'NoneType' object has no attribute 'todict'
2020-02-12 12:51:26,531 - D:/罗京/Projects/cmdb/app.py[line:108] - ERROR: 'NoneType' object has no attribute 'todict'
2020-02-12 12:53:24,431 - D:/罗京/Projects/cmdb/app.py[line:108] - ERROR: 'NoneType' object has no attribute 'todict'
2020-02-12 12:53:43,212 - D:/罗京/Projects/cmdb/app.py[line:108] - ERROR: 'NoneType' object has no attribute 'todict'
2020-02-13 12:38:39,682 - D:/罗京/Projects/cmdb/app.py[line:172] - ERROR: add_entity() got multiple values for keyword argument 'schema_id'
2020-02-13 18:27:09,095 - D:/罗京/Projects/cmdb/app.py[line:341] - ERROR: 'list' object has no attribute 'value'
2020-02-14 02:39:24,983 - D:/罗京/Projects/cmdb/app.py[line:293] - ERROR: Query.get() being called on a Query with existing criterion. 
2020-02-14 16:58:54,142 - D:/罗京/Projects/cmdb/app.py[line:276] - ERROR: Python type Field cannot be converted
2020-02-16 18:21:43,674 - D:/projects/cmdb/app.py[line:423] - ERROR: string argument expected, got 'bytes'
2020-02-16 18:41:57,032 - D:/projects/cmdb/app.py[line:421] - ERROR: cannot import name 'BinaryIO' from 'io' (C:\Users\罗京\AppData\Local\Programs\Python\Python38\lib\io.py)
2020-02-16 18:47:46,046 - D:/projects/cmdb/app.py[line:417] - ERROR: cannot import name 'BinaryIO' from 'io' (C:\Users\罗京\AppData\Local\Programs\Python\Python38\lib\io.py)
2020-02-18 12:06:07,518 - app.py[line:115] - ERROR: 'dict' object has no attribute 'ref'
2020-02-18 12:27:13,665 - app.py[line:116] - ERROR: 'dict' object has no attribute 'ref'
2020-02-18 12:29:16,295 - app.py[line:116] - ERROR: append() takes exactly one argument (2 given)
2020-02-18 12:42:11,359 - app.py[line:116] - ERROR: 'dict' object has no attribute 'name'
2020-02-18 12:48:47,318 - app.py[line:117] - ERROR: name 'f' is not defined
2020-02-18 12:49:34,932 - app.py[line:117] - ERROR: name 'f' is not defined
2020-02-18 12:51:26,806 - app.py[line:116] - ERROR: 'id'
2020-02-18 17:18:16,013 - app.py[line:185] - ERROR: list_entity() got an unexpected keyword argument 'field'
2020-02-18 17:18:54,208 - app.py[line:185] - ERROR: list_entity() got an unexpected keyword argument 'field'
2020-02-18 22:22:59,486 - app.py[line:186] - ERROR: 'list' object has no attribute 'name'
2020-02-18 22:27:02,067 - app.py[line:186] - ERROR: 'list' object has no attribute 'name'
2020-02-18 22:28:29,100 - app.py[line:186] - ERROR: 'list' object has no attribute 'name'
2020-02-19 22:50:46,776 - D:/projects/cmdb/app.py[line:561] - ERROR: 'str' object has no attribute 'value'
2020-02-22 18:32:19,197 - E:\cmdb\app.py[line:153] - ERROR: 'NoneType' object has no attribute 'todict'
2020-02-22 18:32:47,140 - E:\cmdb\app.py[line:153] - ERROR: 'NoneType' object has no attribute 'todict'
2020-02-22 18:40:19,901 - app.py[line:153] - ERROR: 'NoneType' object has no attribute 'todict'
2020-02-22 18:42:06,351 - E:/cmdb/app.py[line:153] - ERROR: 'NoneType' object has no attribute 'todict'
2020-02-22 18:48:03,615 - E:/cmdb/app.py[line:153] - ERROR: 'NoneType' object has no attribute 'todict'
2020-02-22 18:48:47,917 - E:/cmdb/app.py[line:153] - ERROR: 'NoneType' object has no attribute 'todict'
2020-02-22 19:13:21,908 - E:/cmdb/app.py[line:280] - ERROR: 'NoneType' object has no attribute 'get'
2020-02-22 19:16:46,500 - E:/cmdb/app.py[line:281] - ERROR: 'NoneType' object has no attribute 'get'
2020-02-22 19:18:55,166 - E:/cmdb/app.py[line:282] - ERROR: 'NoneType' object has no attribute 'get'
2020-02-22 19:23:12,004 - E:/cmdb/app.py[line:523] - ERROR: 'NoneType' object has no attribute 'value'
2020-02-22 19:33:28,050 - E:\cmdb\app.py[line:186] - ERROR: 'NoneType' object has no attribute 'value'
2020-02-24 10:37:44,944 - E:\cmdb\app.py[line:153] - ERROR: 'NoneType' object has no attribute 'todict'
2020-02-24 10:38:13,197 - E:\cmdb\app.py[line:153] - ERROR: 'NoneType' object has no attribute 'todict'
2020-02-24 10:51:11,808 - E:\cmdb\app.py[line:153] - ERROR: 'NoneType' object has no attribute 'todict'
2020-02-24 10:54:55,884 - E:/cmdb/app.py[line:153] - ERROR: 'NoneType' object has no attribute 'todict'
2020-02-24 10:56:08,764 - E:/cmdb/app.py[line:153] - ERROR: 'NoneType' object has no attribute 'todict'
2020-02-24 11:03:59,200 - E:/cmdb/app.py[line:153] - ERROR: 'NoneType' object has no attribute 'todict'
2020-02-24 11:04:01,602 - E:/cmdb/app.py[line:153] - ERROR: 'NoneType' object has no attribute 'todict'
2020-02-24 11:17:31,653 - E:\cmdb\app.py[line:153] - ERROR: 'NoneType' object has no attribute 'todict'
2020-02-24 11:17:41,291 - E:\cmdb\app.py[line:153] - ERROR: 'NoneType' object has no attribute 'todict'
2020-02-24 11:25:38,276 - E:\cmdb\app.py[line:153] - ERROR: 'NoneType' object has no attribute 'todict'
2020-02-24 11:25:42,009 - E:\cmdb\app.py[line:153] - ERROR: 'NoneType' object has no attribute 'todict'
2020-02-24 11:26:46,724 - E:/cmdb/app.py[line:153] - ERROR: 'NoneType' object has no attribute 'todict'
2020-02-24 11:27:18,837 - E:/cmdb/app.py[line:153] - ERROR: 'NoneType' object has no attribute 'todict'
2020-02-24 11:31:17,469 - E:/cmdb/app.py[line:153] - ERROR: 'NoneType' object has no attribute 'todict'
